### ISSUE TITLE
Check the existence of URL for a different version

### ISSUE THREAD

**Issue by dgomezg** [AxonIQ/axoniq-library-site#37]
Right now, the URL generated in the 'versions' dropdown menu is not checked for existence.

For example. in the Axon Server Guide, the index page in the `master` branch  (corresponding to `development`) has been renamed to `introduction.html`. Meanwhile on the `axonserver-v.2024.1*` branch (corresponding to v 2024.1) version, it is still index.html. 

Thus, when the user selects 'Referece > Axon Server' from the main navigation menu in library.axoniq.io, the main page for the 2024.1 version is loaded in the following URL: https://library.axoniq.io/axon_server_ref/v2024.1/index.html 

If, while in that page, the user selects the 'development' version in the top right menu, the URL that tries to load is the same one except it changes the version part of the URL: https://library.axoniq.io/axon_server_ref/index.html, but that URL does not exists and it should be https://library.axoniq.io/axon_server_ref/introduction.html

**Expected behaviour** 

When selecting a different version, the associated URL should be checked for existence and if the same URL does not exists in the target version, link to the start page for that branch as it is configured on the `antora.yml`descriptor.  If it is not possible to check the existence of the URL, at least the version menu should always point to the start page for that version.

**Comment by SaraTorrey** [comment]
@smcvb is this issue related to your recent work fixing the links with `.html` included at the end?

**Comment by smcvb** [comment]
> @smcvb is this issue related to your recent work fixing the links with `.html` included at the end?

This issue is a combination of that, but also the changes Mitchell did yesterday.
So we can close this ticket as resolved. Good catch!
